language: android

android:
  components:
    # Update Android SDK Tools
    - tools

    - build-tools-"24.0.0 rc4"
    - android-'N'

    # Support library
    - extra-android-support
    - extra-android-m2repository

script:
    - chmod +x ./gradlew
